name: CI

on:
  push:
    branches: [master]
    tags: ["*.*.*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier/v1
            ~/.ivy2/cache
          key: ${{ runner.os }}-build-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}

      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: zulu

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - run: sbt publishLocal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: sbt-updates
          path: /home/runner/.ivy2/local

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'SuperFola/sbt-swaggerinator' && ( github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') )

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier/v1
            ~/.ivy2/cache
          key: ${{ runner.os }}-publish-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}

      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: zulu

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
